# Generated by Django 3.0.5 on 2020-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guidemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=40)),
                ('cwpasswd', models.CharField(max_length=40)),
                ('mobileno', models.CharField(default='', max_length=50)),
                ('location', models.CharField(max_length=40)),
                ('status', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
            ],
        ),
    ]
